name: CI

on:
  push:
    branches:
      - master
      - cx
  pull_request:
    branches:
      - '*'

jobs:
  combine:
    runs-on: macOS-latest
    strategy:
      matrix:
        xcode:
          - 11.3
          - 11.4
          - 11.5
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Run tests
        run: make test-swift

  cx:
    runs-on: macOS-latest
    env:
      CX_COMBINE_IMPLEMENTATION: CombineX
      CX_CONTINUOUS_INTEGRATION: "YES"
    strategy:
      matrix:
        xcode:
          - 11.5
    steps:
      - uses: actions/checkout@v2
      - name: Select Xcode ${{ matrix.xcode }}
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
      - name: Run tests
        run: make test-swift

  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift_version: 
          - 5.2
    container:
      image: swift:${{ matrix.swift_version }}
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: make test-swift
